### ISSUE TITLE
Web Components

### ISSUE THREAD

**Issue by AlbertSanIza** [Involt/Involt#25]
How about if we use web components with data binding, instead of baking in all functionality to involt.js?

**Comment by ErniW** [comment]
Could you give me an example on using web components? How this will affect the framework usage from the user side?

I was thinking about data binding because it allows to work correctly with JQuery .append() and it makes JQuery more flexible. Currently I've finished the new update which adds Involt related jquery methods to simplify creating custom scripts (I was working on this for some time). Maybe this could be new step for project.

From the other side data binding can be both side- it can update elements automatically (currently it's only for data read) but in my opinion this will cause performance issues with current receiving data from Arduino function.
