### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getDevices' of undefinedInvolt.getDevices @ 

### ISSUE THREAD

**Issue by spagu** [Involt/Involt#67]
(newbie) Fresh installation using manual - and this error:

Uncaught TypeError: Cannot read property 'getDevices' of undefinedInvolt.getDevices @ involt.js:424(anonymous function) @ involt.js:937

**Comment by ErniW** [comment]
You must install this as chrome packaged app, instruction is in readme or getting started page.

**Comment by spagu** [comment]
Done exacly as in readme, It asks for COM port then connect. Then it just gives this error.

**Comment by ErniW** [comment]
Hmm ok, so Involt detects the ports in loader, you select the port and then this error occurs? Then getDevices (and Involt) do work correctly at all because without that you couldn't even see your ports.

Could you give me some details - what system and what arduino do you use, did you changed something in files, maybe try again using chrome apps and extensions developer tools (https://chrome.google.com/webstore/detail/chrome-apps-extensions-de/ohmmkhmmmpcnpikjeljgnaoabkaalbgc?hl=en)
